// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByF2Mg03o6EdcBkhlYEdyvS38QbKSojhg',
    appId: '1:941807989167:web:0c3d44e7c2d25106377f5a',
    messagingSenderId: '941807989167',
    projectId: 'app-lista-tarefas-engcom-bf5de',
    authDomain: 'app-lista-tarefas-engcom-bf5de.firebaseapp.com',
    storageBucket: 'app-lista-tarefas-engcom-bf5de.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCfRkjD_tQ1PLyCNNVj5Fhv2F8cTZMQPQ',
    appId: '1:941807989167:android:2076d1115b2d810b377f5a',
    messagingSenderId: '941807989167',
    projectId: 'app-lista-tarefas-engcom-bf5de',
    storageBucket: 'app-lista-tarefas-engcom-bf5de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSgfMiVOP_CkXekWsSEWBL9QGjrFbMQbM',
    appId: '1:941807989167:ios:e67e65410caf9709377f5a',
    messagingSenderId: '941807989167',
    projectId: 'app-lista-tarefas-engcom-bf5de',
    storageBucket: 'app-lista-tarefas-engcom-bf5de.appspot.com',
    iosBundleId: 'com.example.app08',
  );

}